yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
] 

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
   path('', include('posts.urls', namespace='posts')),
   path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
# Из модуля auth импортируем функцию get_user_model
from django.contrib.auth import get_user_model

User = get_user_model() 
class Group(models.Model):
    title = models.CharField(max_length = 200)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    
    def __str__(self) -> str:
        return self.title

class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True, null=True,
        on_delete=models.CASCADE,
        related_name='posts'
    )

yatube/posts/views.py
from turtle import title
from django.shortcuts import render, get_object_or_404
from .models import Post, Group

# Create your views here.

def index(request):
    posts = Post.objects.order_by('-pub_date')[:10]
    title = 'Это главная страница проекта Yatube'
    templates = 'posts/index.html'
    context = {
        'title': title,
        'posts': posts,
    }
    return render(request, templates, context)

def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    title = f'Зписи сообщества {group.title}'
    templates = 'posts/group_list.html'
    context = {
        'group': group,
        'posts': posts,
        'title': title,
    }
    return render(request, templates, context) 

yatube/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <title>{{ title }}</title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
    </main>
    <footer>
      {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
    <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>    
  </footer>

yatube/templates/includes/header.html
{% load static %}
<header>
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href="{% url 'posts:index' %}">
          <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
          <span style="color:red">Ya</span>tube
        </a>
      </div>
    </nav>
</header>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{%block title %}
Группы проекта Yatube
{%endblock %}
{%block content%}
<body>
    <main>
      <div class="container py-5">
        <h1> Лев Толстой – зеркало русской революции. </h1>
        <p>
          Группа тайных поклонников графа.
        </p>
        <article>
          {% for post in posts %}
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>{{ post.text }}</p>
          {% if post.group %}   
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
          {% endfor %} 
        </article>
        <hr>
      </div>
    </main>
  </body>
{%endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<body>
    <main>
      <div class="container py-5">
        <h1> Последние обновления на сайте </h1>
        <article>
          {% for post in posts %}
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
            {% if post.group %}   
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
            <p>{{ post.text }}</p>    
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %} 
        </article>
        <hr>
      </div>
    </main>>
</body>
{%endblock %}